snap: Fix snap build with kernel fragments
Fixes: #438

Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -193,28 +193,33 @@ parts:
       versions_url=https://raw.githubusercontent.com/kata-containers/runtime/${SNAPCRAFT_PROJECT_VERSION}/versions.yaml
       version="$(curl -sSL ${versions_url} | yq r - assets.kernel.version | tr -d v)"
       x_version="$(echo $version | sed -e 's|.[[:digit:]]*$||').x"
-      case "$(arch)" in
-        "x86_64")
-          config="x86_64_kata_kvm_${x_version}"
-        ;;
+      archfragdir="${SNAPCRAFT_STAGE}/kernel/configs/fragments/$(arch)"
+      if [ -f "${archfragdir}/.config" ]; then
+        config="fragments/$(arch)/.config"
+      else
+        case "$(arch)" in
+          "x86_64")
+            config="x86_64_kata_kvm_${x_version}"
+          ;;
 
-        "ppc64le")
-          config="powerpc_kata_kvm_${x_version}"
-        ;;
+          "ppc64le")
+            config="powerpc_kata_kvm_${x_version}"
+          ;;
 
-        "aarch64")
-          config="arm64_kata_kvm_${x_version}"
-        ;;
+          "aarch64")
+            config="arm64_kata_kvm_${x_version}"
+          ;;
 
-        "s390x")
-          config="s390_kata_kvm_${x_version}"
-        ;;
+          "s390x")
+            config="s390_kata_kvm_${x_version}"
+          ;;
 
-        *)
-          echo "ERROR: Unsupported architecture $(arch)"
-          exit 1
-        ;;
-      esac
+          *)
+            echo "ERROR: Unsupported architecture $(arch)"
+            exit 1
+          ;;
+        esac
+      fi
 
       make mrproper
 
